MyTask/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',views.showIndex),
    path('welcome/',views.welcomePage,name="welcome")
]

app/models.py
from django.db import models

# Create your models here.
class Register(models.Model):
    fname=models.CharField(max_length=30)
    lname=models.CharField(max_length=30)
    phonenumber=models.CharField(max_length=10)

app/views.py
from django.shortcuts import render
from app.models import Register
# Create your views here.
def showIndex(request):
    return render(request,'index.html')


def welcomePage(request):
    fname=request.POST['fname']
    lname = request.POST['lname']
    pnumber= request.POST['pnumber']
    Register(fname=fname,lname=lname,phonenumber=pnumber).save()
    return render(request,'welcome.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'welcome' %}" method="post">
    {% csrf_token %}
    <table align="center">
        <tr>
            <th>First Name:</th>
            <th><input type="text" name="fname" id="id_fname" required></th>
        </tr>
        <tr>
            <th>Last Name:</th>
            <th><input type="text" name="lname"  id="id_lname" required></th>
        </tr>
        <tr>
            <th>Phone Number:</th>
            <th><input type="number" name="pnumber"  id="id_pnumber"required></th>
        </tr>
        <tr>
            <th><button type="submit" name="welcome">Submit</button></th>
        </tr>
    </table>

</form>
</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>WELCOME</h1>
</body>
</html>